### PR TITLE
Different policies depending on whether FIPS or not

### LINKED ISSUE #43: Try `cached` touch policy before defaulting to `on`
Unfortunately, #42 won't work for everyone, especially those with the FIPS key model. Therefore, we should default to the `on` touch policy after trying `cached` and it fails.

Cc @HadrienPatte

### PR DESCRIPTION
**Pull request by trishankatdatadog**
Fixes #43, among other things

### CODE REVIEW

**Comment by srosenthal-dd** [comment]
Hey! I'd be happy to test this out. Can you recommend how to do it?

I run into the `WARNING! This will delete all stored OpenPGP keys and data and restore factory settings?` and get a bit worried. I think it means that I'll lose my old key, so I'll need to update my key in GitHub and the PINs in 1Password. Is that right?

**Comment by srosenthal-dd** [comment]
So far, the key-type detection works nicely.

```
YubiKey device type: YubiKey 5C Nano
Which does not appear to be a FIPS key
```

**Comment by srosenthal-dd** [comment]
OK I'm testing it out now. It's getting stuck, but I haven't figured out why yet. Here's how far it gets:

```
gpg/card> admin
Admin commands are allowed

gpg/card> passwd
gpg: OpenPGP card no. D2760001240103040006115846500000 detected

1 - change PIN
2 - unblock PIN
3 - change Admin PIN
4 - set the Reset Code
Q - quit

Your selection? 1
Please enter the PIN
PIN:
New PIN
PIN:
Repeat this PIN
PIN:
PIN changed.

1 - change PIN
2 - unblock PIN
3 - change Admin PIN
4 - set the Reset Code
Q - quit

Your selection? 3
Error changing the PIN: Bad PIN

1 - change PIN
2 - unblock PIN
3 - change Admin PIN
4 - set the Reset Code
Q - quit

Your selection?
```

**Comment by trishankatdatadog** [comment]
Thanks very much, Stephen! I will wait for one more independent testing and approval...

**Comment by daisukixci** [comment]
Will test this weekend

**Comment by daisukixci** [comment]
Failed with a FIPS key 
image

**Comment by daisukixci** [comment]
image
The detection was good though

**Comment by daisukixci** [comment]
I think it's because you didn't replace https://github.com/DataDog/yubikey/pull/45/files#diff-7da6c05cf9823dfcb1c4ecb82a799fb8R205 for using TOUCH_POLICY

**Comment by daisukixci** [comment]
Pushed a commit to make it work in both case. But testing it with all my keys (4/5 usb A/C), I learned that cached doesn't work with all keys even the not FIPS one (https://developers.yubico.com/PIV/Introduction/Yubico_extensions.html). It came with a specific firmware version. So I think we need to find the version and manage that case too before merging

**Comment by daisukixci** [comment]
Found https://github.com/Yubico/yubikey-manager/issues/277#issuecomment-529805540 that says that it works since 5.2.3

File: expect.sh [hunk 1]
```diff
@@ -204,14 +202,19 @@ expect eof
...
+spawn ykman openpgp set-touch sig $TOUCH_POLICY
 
 expect -exact "Enter admin PIN: "
 stty -echo
 send -- "$PUK\r"
 
-expect -exact "Set touch policy of signature key to cached? \[y/N\]: "
-send -- "y\r"
+if {[string equal $TOUCH_POLICY "cached"]} {
+    expect -exact "Set touch policy of signature key to cached? \[y/N\]: "
```
Comment (trishankatdatadog) [inline expect.sh:212]: Instead of using an IF condition here, why not just use one string with the $TOUCH_POLICY set?

Comment (daisukixci) [reply expect.sh:212]: done

**Comment by daisukixci** [comment]
Tested it with 3 yubikeys:
* 1 FIPS
* 1 USB C firmware < 5.2.3
* 1 USB A firmware < 5.2.3
Doesn't have a non production Yubikey where firmware is >= 5.2.3 ? @srosenthal-dd do you have the capacity to test it with the same you already test it ?

File: gpg.sh [hunk 2]
```diff
@@ -188,8 +199,8 @@ echo
 
 # Final reminders.
 echo "Finally, remember that your keys will not expire until 10 years from now."
-echo "You will need to ${RED}${BOLD}enter your PIN (once a day)${RESET}, and ${RED}${BOLD}touch your YubiKey every time${RESET} in order to sign any message with this GPG key."
-if [[ "$YUBIKEY_FIPS" == "true" ]]; then
+echo "You will need to ${RED}${BOLD}enter your PIN (once a day)${RESET}, and ${RED}${BOLD}touch your YubiKey${RESET} in order to sign any message with this GPG key."
+if [[ "$YUBIKEY_CACHE" == "true" ]]; then
```
Comment (trishankatdatadog) [inline gpg.sh:203]: Let's call it `YUBIKEY_FIPS`, please, because that's the real root cause

Comment (daisukixci) [reply gpg.sh:203]: It's not it's because of the firmware version and FIPS keys are 4.X.X version because only this version has been approved FIPS compliant

**Comment by trishankatdatadog** [comment]
> * Doesn't have a non production Yubikey where firmware is >= 5.2.3 ? @srosenthal-dd do you have the capacity to test it with the same you already test it ?

Perhaps easiest to test it by setting a version number we can control

File: gpg.sh [hunk 3]
```diff
@@ -52,15 +52,26 @@ if [[ "$DEVICE_TYPE" == *"YubiKey FIPS"* ]]; then
...
   echo "Which does not appear to be a FIPS key"
   YUBIKEY_FIPS=false
   KEY_LENGTH=4096
+fi
+# Activate cache policy if possible (when firmware version equal or superior to 5.2.3
+# https://github.com/Yubico/yubikey-manager/issues/277#issuecomment-529805540
+FIRMWARE_VERSION=$($YKMAN info | grep 'Firmware version:' | cut -f2 -d: | awk '{$1=$1;print}')
+set +e
+vercomp "$FIRMWARE_VERSION" 5.2.3
+if [[ "$?" -eq 2 ]]; then
```
Comment (trishankatdatadog) [inline gpg.sh:65]: Just to be on the [safe side](https://github.com/Yubico/yubikey-manager/issues/277#issuecomment-661242728), I'd also check for whether `YUBIKEY_FIPS` is true here

File: gpg.sh [hunk 4]
```diff
@@ -52,15 +52,26 @@ if [[ "$DEVICE_TYPE" == *"YubiKey FIPS"* ]]; then
...
+  echo "Firware version is inferior to 5.2.3, setting touch policy to on"
+  YUBIKEY_CACHE=false
+  TOUCH_POLICY=on
+else
+  echo "Firware version is superior or equal to 5.2.3, setting touch policy to cached"
+  YUBIKEY_CACHE=true
```
Comment (trishankatdatadog) [inline gpg.sh:71]: No need for a new `YUBIKEY_CACHE` variable, we can just check `TOUCH_POLICY`, please

File: gpg.sh (hunk 3 above)
Comment (daisukixci) [reply gpg.sh]: done

File: gpg.sh (hunk 4 above)
Comment (daisukixci) [reply gpg.sh]: done

File: gpg.sh [hunk 5]
```diff
@@ -62,13 +62,11 @@ fi
 FIRMWARE_VERSION=$($YKMAN info | grep 'Firmware version:' | cut -f2 -d: | awk '{$1=$1;print}')
 set +e
 vercomp "$FIRMWARE_VERSION" 5.2.3
-if [[ "$?" -eq 2 ]]; then
+if [[ "$?" -eq 2 ]] || [[ "$YUBIKEY_FIPS" == "true" ]]; then
   echo "Firware version is inferior to 5.2.3, setting touch policy to on"
```
Comment (trishankatdatadog) [inline gpg.sh:66]:
```suggestion
  echo "Setting touch policy to on"
```

File: gpg.sh [hunk 6]
```diff
@@ -62,13 +62,11 @@ fi
...
-  YUBIKEY_CACHE=false
   TOUCH_POLICY=on
 else
   echo "Firware version is superior or equal to 5.2.3, setting touch policy to cached"
```
Comment (trishankatdatadog) [inline gpg.sh:69]:
```suggestion
  echo "Setting touch policy to cached"
```
