### PR TITLE
Fix most shellcheck issues

### LINKED ISSUE #39: Run shellcheck
https://github.com/koalaman/shellcheck

### PR DESCRIPTION
**Pull request by trishankatdatadog**
Fixes #39. Needs testing.

Signed-off-by: Trishank Karthik Kuppusamy <trishank.kuppusamy@datadoghq.com>

### CODE REVIEW

File: ssh.sh [hunk 1]
```diff
@@ -25,9 +25,9 @@ function configure_shell {
     echo "$config_file_basename detected"
     if ! grep -q "gpg-agent.ssh" "$config_file"; then
         if [[ "$config_file_basename" == "config.fish" ]]; then
-            echo 'set -gx SSH_AUTH_SOCK ${HOME}/.gnupg/S.gpg-agent.ssh' >> "${config_file}"
+            echo "set -gx SSH_AUTH_SOCK ${HOME}/.gnupg/S.gpg-agent.ssh" >> "${config_file}"
         else
-            echo 'export "SSH_AUTH_SOCK=${HOME}/.gnupg/S.gpg-agent.ssh"' >> "${config_file}"
+            echo "export \"SSH_AUTH_SOCK=${HOME}/.gnupg/S.gpg-agent.ssh\"" >> "${config_file}"
```
Comment (daisukixci) [inline ssh.sh:30]: Is it a shellcheck error or a warning because it looks like a false positive as the tool see the $var but can't know you want the literal version of it

Comment (trishankatdatadog) [reply ssh.sh:30]: Yeah, can we ignore this with a directive?

Comment (daisukixci) [reply ssh.sh:30]: Yes we can comment above each echo # shellcheck disable=SHELLCHECK_TEST_CODE where SHELLCHECK_TEST_CODE should look like SC1000

Comment (trishankatdatadog) [reply ssh.sh:30]: Ok, ignored the remaining couple of shellcheck warnings, they don't seem worth it

File: realname-and-email.sh [hunk 2]
```diff
@@ -10,7 +10,7 @@ source env.sh
 # 1. Real name.
 REALNAME=$($GIT config --global --default '' --get user.name)
 echo "What is the real name you use on GitHub?"
-read -p "Real name (press Enter to accept '$REALNAME'): " input
+read -pr "Real name (press Enter to accept '$REALNAME'): " input
```
Comment (daisukixci) [inline realname-and-email.sh:13]: This fails:
`+ source realname-and-email.sh
++ set -e
++ source env.sh
++++ brew --prefix
+++ HOMEBREW_PREFIX=/usr/local
+++ HOMEBREW_BIN=/usr/local/bin
+++ export GIT=/usr/local/bin/git
+++ GIT=/usr/local/bin/git
+++ export GPG=/usr/local/bin/gpg
+++ GPG=/usr/local/bin/gpg
+++ export GPG_AGENT=/usr/local/bin/gpg-agent
+++ GPG_AGENT=/usr/local/bin/gpg-agent
+++ export GPGCONF=/usr/local/bin/gpgconf
+++ GPGCONF=/usr/local/bin/gpgconf
+++ export YKMAN=/usr/local/bin/ykman
+++ YKMAN=/usr/local/bin/ykman
++++ tput bold
+++ BOLD=''
+++ export BOLD
++++ tput setaf 1
+++ RED=''
+++ export RED
++++ tput sgr0
+++ RESET=''
+++ export RESET
+++ export SSH_ENV=/Users/gaetan.piquenot/.ssh/environment
+++ SSH_ENV=/Users/gaetan.piquenot/.ssh/environment
+++ DEFAULT_GPG_HOMEDIR=/Users/gaetan.piquenot/.gnupg
+++ DEFAULT_GPG_AGENT_CONF=/Users/gaetan.piquenot/.gnupg/gpg-agent.conf
+++ /usr/local/bin/git config --global --default '' --get user.name
++ REALNAME=daisukixci
++ echo 'What is the real name you use on GitHub?'
What is the real name you use on GitHub?
++ read -pr 'Real name (press Enter to accept '\''daisukixci'\''): ' input
realname-and-email.sh: line 13: read: `Real name (press Enter to accept 'daisukixci'): ': not a valid identifier`

Comment (daisukixci) [reply realname-and-email.sh:13]: removing the -r fixed the issue

Comment (daisukixci) [reply realname-and-email.sh:13]: `-rp`instead of `-pr`works

Comment (trishankatdatadog) [reply realname-and-email.sh]: Done, boss

**Review by daisukixci — APPROVED** [review]
