### PR TITLE
Fix an edge case when expect is not able to fill some steps

### LINKED ISSUE #50: Issue with PIN not being typed
I'm trying to get this awesome setup working but when running `./gpg.sh` it hangs when trying to change the PIN. It correctly selects the option `1` but then it never types the pin, after it timesout I can see the `123456`.

Eg:
```
gpg/card> admin
Admin commands are allowed

gpg/card> passwd
gpg: OpenPGP card no. <redacted> detected

1 - change PIN
2 - unblock PIN
3 - change Admin PIN
4 - set the Reset Code
Q - quit

Your selection? 1
Please enter the PIN
PIN:
Error changing the PIN: Timeout

1 - change PIN
2 - unblock PIN
3 - change Admin PIN
4 - set the Reset Code
Q - quit

Your selection? 123456
```

I tried bumping the sleep in `expect.sh` to `1`, switching from zsh to bash, but I can't seem to figure out what is going on, I can't get it to type it at the right time.

Any help would be greatly appreciated.

### PR DESCRIPTION
**Pull request by daisukixci**
fix #50 

Huge thanks to @ahmed-mez who find the solution. 

The script failed to run when `GPG_TTY != ''` so we ensure it's empty before the expect script.

https://gnupg.org/documentation/manuals/gnupg/Common-Problems.html

### CODE REVIEW

File: gpg.sh [hunk 1]
```diff
@@ -178,6 +178,7 @@ export LC_ALL=en_US.UTF-8
 # drive yubikey setup
 # but right before, kill all GPG daemons to make sure things work reliably
 $GPGCONF --homedir="$GPG_HOMEDIR" --kill all
+export GPG_TTY=""
```
Comment (trishankatdatadog) [inline gpg.sh:181]: Why not just set the env var specific to the expect.sh run?

Comment (daisukixci) [reply gpg.sh]: done

Comment (trishankatdatadog) [reply gpg.sh]: One more thing: please add a comment right above on why that flag seems critical?

Comment (daisukixci) [reply gpg.sh]: done

**Review by trishankatdatadog — APPROVED** [review]
